name: "Ollama PR Reviewer"
description: "A JavaScript GitHub Action that retrieves the git diff of a pull request and reviews using the Ollama API."

inputs:
  model:
    description: "Ollama model name and version. Eg. 'codellama:7b'"
    required: true

  base-url:
    description: "The base URL of the Ollama endpoint. Eg. http://127.0.0.1:11434"
    required: true

  prompt:
    description: "A multiline string input that provides detailed instructions to the LLM."
    default: |
      Please review the following git diff and provide brief feedback on:

      Code Quality: Any improvements needed?
      Functionality: Any issues or bugs?
      Performance: Any potential impacts?
      Security: Any concerns?
      Documentation: Any missing comments?

      Here's the git diff:

runs:
  using: "node20"
  main: "dist/index.js"
