name: "Review Action"
description: "JS Action to review code using local Ollama API"

inputs:
  concurrency:
    description: Number of API calls to make concurrently
    required: true
    default: 2

  model:
    description: "Name of the Ollama model"
    required: true

  git_diff_file_path:
    description: Abs file path of git diff .txt file
    required: true

  prompt:
    description: Prompt
    default: "Review the following code"

runs:
  using: "node20"
  main: "dist/index.js"
